### ISSUE TITLE
Update readme for Orders CLI MVP milestone

### ISSUE THREAD

**Issue by cholmes** [planetlabs/planet-client-python#453]
So I think we need a few updates to [the README](https://github.com/planetlabs/planet-client-python/blob/v2/README.md) for v2, in order to achieve the Orders CLI MVP milestone.

I don't think we need a very advanced 'install' story, it needs to be good enough for a motivated person who is fairly comfortable with the command line and ok to check out the repo. I _think_ at the least it needs to say `pip install .` instead of `pip install planet`. Though with #408 and a cut release we may be able to do `pip install planet2`? I could see putting `pip install .` in 'contributing' under a 'build from source' type of directions, but I think we need to at least link from there in the readme.

Other thing the readme needs / will need:

* [x] Link to the v1 branch, after #368 and #367 
* [x] Explain the situation of v1 vs v2, especially the state of stability / completeness of v2.
* [x] Update to the quickstart list - we should have it say orders, data and subscriptions, and perhaps link to the milestones with the 'unimplemented', and then mention that we plan in future versions to support analytics, basemaps and tasking.
* [ ] Quickstart should show a CLI example, not a python API example (perhaps move that down to a directory / to another file and then link to 'python API examples', as we want to focus on the CLI.
* [x] Link to the 'docs' directory, instead of just saying `docs` and making people click through the source code.
